### ISSUE TITLE
[Feature Suggestion] IPinfo's free IP database - IP to Country ASN

### ISSUE THREAD

**Issue by abdullahdevrel** [devoxa/ip-geolocation#677]
I think [IPinfo's free IP database](https://ipinfo.io/products/free-ip-database) would be able to provide tremendous value by providing both country and ASN data to the project.

The features of the [free IP to Country ASN database](https://ipinfo.io/developers/ip-to-country-asn-database):

- Provides full accuracy with daily updates and no IP range aggregation. The accuracy of IP data is provided on a granular level.
- Combines both country and ASN information in a single database.
- Comes in MMDB file format.
- The database structure is flat, tabular and consistent.
- Released under a commercially permissible CC-BY-SA 4.0 license.

Schema: https://ipinfo.io/developers/ip-to-country-asn-database

| FIELD NAME     | EXAMPLE                      | DATA TYPE | DESCRIPTION                                       |
|----------------|------------------------------|-----------|---------------------------------------------------|
| start_ip       | 1.0.16.0                     | TEXT      | Starting IP address of an IP address range        |
| end_ip         | 1.0.31.255                   | TEXT      | Ending IP address of an IP address range          |
| country        | JP                           | TEXT      | ISO 3166 country code of the location             |
| country_name   | Japan                        | TEXT      | Name of the country                               |
| continent      | AS                           | TEXT      | Continent code of the country                     |
| continent_name | Asia                         | TEXT      | Name of the continent                             |
| asn            | AS2519                       | TEXT      | Autonomous System Number                          |
| as_name        | ARTERIA Networks Corporation | TEXT      | Name of the AS (Autonomous System) organization   |
| as_domain      | arteria-net.com              | TEXT      | Official domain or website of the AS organization |

Please let me know what you think. If you need any assistance, I will be happy and glad to help.

**Comment by queicherius** [comment]
My personal use-case is to resolve IPs to city-level granularity, which the DB you linked does not seem to provide. I also personally have no use for ASN, and loading yet another 50MB and having to have yet another attribution link does not seem worth it.

If you personally need ASN, feel free to open a PR with this DB https://db-ip.com/db/download/ip-to-asn-lite instead, since it shares the same attribution + is much smaller.
